name: Node.js CI
on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm install yarn@latest
      - run: yarn install
      - run: yarn build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_barnch: gh-pages
          publish_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_REPO_TOKEN }}
